name: Makefile CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
        - macos-latest
	linking:
	- dynamic
	- static

    env:
      LINKING: ${{ matrix.linking }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build project
        run: make
