name: Makefile CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

stages:
  - lint
  - build

jobs:
  check:
    stage: lint
    when: always
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Lint project
        run: make lint
    

  build:
    stage: build
    when: on_success
    
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
        - macos-latest
        linking:
        - dynamic
        - static
        compiler:
        - gcc
        - clang

    env:
      LINKING: ${{ matrix.linking }}
      COMPILER: ${{ matrix.compiler }}
      BUILD: release
      STRICT: strict

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Build project
        run: make
